package com.esewa.restchangerequestapproval.shared;

public enum Department {
    NETWORK_ADMINISTRATION,
    SYSTEMS_ADMINISTRATION,
    CYBERSECURITY,
    SOFTWARE_DEVELOPMENT,
    HELP_DESK_TECHNICAL_SUPPORT,
    HUMAN_RESOURCES,
    FINANCE_AND_ACCOUNTING,
    INFORMATION_TECHNOLOGY,
    MARKETING,
    SALES,
    OPERATIONS
}
