package com.esewa.restchangerequestapproval.shared;

public enum Department {
    HUMANRESOURCES,
    FINANCEANDACCOUNTING,
    MARKETING,
    SALES,
    OPERATIONS,
    INFORMATIONTECHNOLOGY,
    CUSTOMERSERVICE,
    RESEARCHANDDEVELOPMENT,
    LEGAL,
    ADMINISTRATION,
    QUALITYASSURANCE,
    BUSINESSDEVELOPMENT,
    CORPORATECOMMUNICATIONS,
    TRAININGANDDEVELOPMENT,
    STRATEGYANDPLANNING
}
